name: Docker
description: Builds a docker image and optionally push it
author: batinicaz
inputs:
  image_name:
    description: The name of the image being built
    default: ghcr.io/${{ github.repository }}
    required: false
  image_tag:
    description: The tag of the image being built
    default: latest
    required: false
  registry:
    description: The container registry that will be used for image pushing
    default: ghcr.io
    required: false
  push:
    description: Push the image to the container registry?
    default: "false"
    required: false
  token:
    description: Token to authenticate with registry. Required if pushing
    default: ""
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v5
    - name: Login to GitHub Container Registry
      if: ${{ inputs.push }}
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # ratchet:docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    - name: Build image
      run: |
        docker build -t ${{ inputs.image_name }}:${{ inputs.image_tag }} .
      shell: bash
    - name: Push Docker image
      run: |
        if [[ "${{ inputs.push }}" == "true" ]]; then
          docker push ${{ inputs.image_name }}:${{ inputs.image_tag }}
        else
          echo 'Push skipped'
        fi
      shell: bash
